[app]
logger = true
requireTokens = true

[database]
host = 'localhost'
port = 3306
user ='citazionet'
password = 'citazionet'
database = 'citazionet'
connectionLimit = 20

[sessions]
# we recommend using `openssl rand -base64 128` to generate a secure session secret :)
secret = """swap this out!! or else i'm gonna come and get your unsafe ass"""

[sessions.cookie]
# https://github.com/fastify/session#cookie
maxAge = 1800000
httpOnly = true
secure = "auto"

[sessions.storage]
# https://www.npmjs.com/package/express-mysql-session#Options
host = 'localhost'
port = 3306
user ='citazionet'
password = 'citazionet'
database = 'citazionet'
connectionLimit = 1

[server]
host= 'localhost'
port= 3000