[app]
logger = true
requireTokens = false

[database]
host = 'localhost'
port = 3306
user ='citazionet'
password = 'citazionet'
database = 'citazionet'
connectionLimit = 4

[sessions]
# we recommend using `openssl rand -base64 128` to generate a secure session secret :)
secret = """swap this out!! or else i'm gonna come and get your unsafe ass"""

[sessions.cookie]
# https://github.com/fastify/session#cookie
maxAge = 1800000
httpOnly = true
secure = "auto"

[server]
host= 'localhost'
port= 3000
crossOrigin = true

[turnstile]
secret = "1x0000000000000000000000000000000AA"

[server.rateLimit]
enabled = true
maxRequests = 10
timeWindow = 1000