/*
 CREATE DATABASE THEYSAID;
 USE THEYSAID;
 CREATE USER THEYSAID@'LOCALHOST' IDENTIFIED BY 'THEYSAID';
 GRANT ALL PRIVILEGES ON THEYSAID.* TO THEYSAID@'LOCALHOST';
 */

drop database citazionet;
create database citazionet;
use citazionet;