db_url = "mysql://theysa_user:theysa_pass@localhost:3306/theysa_db"
bindings = ["0.0.0.0:1111", "0.0.0.0:3000"]
session_duration = { secs = 10, nanos = 0 }
session_secret = "we recommend using `openssl rand -base64 128` to generate a secure session cookie key :)"